# Usamos nginx:alpine por ser la opción más ligera
FROM nginx:alpine

# Copiamos todo el contenido del ejercicio a la ruta /lab02
COPY . /usr/share/nginx/html/lab02

# Exponemos el puerto 80 del contenedor
EXPOSE 80